# Generated by Django 2.1.8 on 2019-11-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=50, verbose_name='商家姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='商家邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='商家密码')),
                ('image', models.ImageField(default='https://source.unsplash.com/QAB-WJcbgJk/60x60', upload_to='media/manage/image')),
                ('is_login', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': '商家',
                'verbose_name': '商家',
            },
        ),
    ]
